server:
  port: 9092

spring:
  application:
    name: DemoB
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:data.d
    username: 
    password: 
  jpa:
    database-platform: org.sqlite.hibernate.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: false

jaeger:
  collector:
    address: http://localhost:14250

frog:
  opentelemetry:
    enable: false